import json
import os
import re
import sqlite3
from collections import Counter
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path

from config.settings import PROJECT_ROOT, Settings
from output.ai_intelligence_report import (
    OUTPUT_DIR as AI_REPORT_OUTPUT_DIR,
    _current_week_label,
    load_ai_intelligence_context,
)


DEFAULT_VAULT_PATH = PROJECT_ROOT / "data" / "output" / "ai_intelligence_vault"
GENERATED_MARKER = "<!-- generated by telegram-research-agent:ai-intelligence -->"


@dataclass(frozen=True)
class ObsidianExportSummary:
    week_label: str
    vault_root: str
    files_written: int
    thread_count: int
    source_atom_count: int
    term_note_count: int
    channel_note_count: int
    read_queue_note_count: int
    experiment_note_count: int


class ObsidianExportError(ValueError):
    pass


def _utc_now_iso() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")


def _slug(value: object) -> str:
    text = str(value or "").strip().lower()
    text = re.sub(r"[^a-z0-9]+", "-", text).strip("-")
    return text or "untitled"


def _vault_root(vault_path: str | Path | None, namespace: str | None) -> Path:
    raw_root = Path(vault_path or os.environ.get("AI_INTELLIGENCE_VAULT_PATH", "") or DEFAULT_VAULT_PATH)
    root = raw_root.expanduser()
    ns = str(namespace or "").strip().strip("/")
    if not ns:
        return root
    ns_path = Path(ns)
    if ns_path.is_absolute() or any(part == ".." for part in ns_path.parts):
        raise ObsidianExportError("namespace must be a relative path without '..'")
    return root / ns_path


def _json_array(values: list | tuple) -> str:
    return json.dumps(list(values), ensure_ascii=False)


def _frontmatter(fields: dict[str, object]) -> str:
    lines = ["---"]
    for key, value in fields.items():
        if isinstance(value, (list, tuple)):
            rendered = _json_array(value)
        elif isinstance(value, bool):
            rendered = "true" if value else "false"
        elif value is None:
            rendered = "null"
        elif isinstance(value, (int, float)):
            rendered = str(value)
        else:
            rendered = json.dumps(str(value), ensure_ascii=False)
        lines.append(f"{key}: {rendered}")
    lines.append("---")
    return "\n".join(lines)


def _note(
    *,
    note_type: str,
    title: str,
    body: str,
    extra_frontmatter: dict[str, object] | None = None,
) -> str:
    frontmatter = {
        "type": note_type,
        "title": title,
        "generated": True,
        "generated_from": "telegram-research-agent",
        "generated_at": _utc_now_iso(),
    }
    frontmatter.update(extra_frontmatter or {})
    return f"{_frontmatter(frontmatter)}\n{GENERATED_MARKER}\n\n# {title}\n\n{body.rstrip()}\n"


def _wiki(path_without_suffix: str, label: str | None = None) -> str:
    clean = path_without_suffix.strip("/")
    if label:
        return f"[[{clean}|{label}]]"
    return f"[[{clean}]]"


def _source_refs(urls: list[str], *, fallback: str = "No source references available yet.") -> str:
    unique = []
    for url in urls:
        clean = str(url or "").strip()
        if clean and clean not in unique:
            unique.append(clean)
    lines = ["## Source References"]
    if unique:
        lines.extend(f"- {url}" for url in unique)
    else:
        lines.append(f"- {fallback}")
    return "\n".join(lines)


def _all_atoms(threads: list[dict]) -> list[dict]:
    atoms = []
    seen = set()
    for thread in threads:
        for atom in thread.get("atoms") or []:
            if atom["id"] in seen:
                continue
            seen.add(atom["id"])
            atoms.append(atom)
    return atoms


def _all_source_urls(threads: list[dict]) -> list[str]:
    return [url for atom in _all_atoms(threads) for url in atom.get("source_urls") or []]


def _report_path_for_week(week_label: str, report_root: str | Path | None) -> Path:
    root = Path(report_root) if report_root is not None else AI_REPORT_OUTPUT_DIR
    return root / f"{week_label}.html"


def _write_generated_note(path: Path, content: str) -> None:
    if path.exists():
        existing = path.read_text(encoding="utf-8")
        if GENERATED_MARKER not in existing:
            raise ObsidianExportError(f"refusing to overwrite hand-authored note: {path}")
    validate_generated_markdown(content, path=path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def validate_generated_markdown(content: str, *, path: Path | None = None) -> None:
    label = str(path) if path else "generated note"
    if not content.startswith("---\n"):
        raise ObsidianExportError(f"{label}: missing frontmatter")
    if GENERATED_MARKER not in content:
        raise ObsidianExportError(f"{label}: missing generated marker")
    if "[[" not in content:
        raise ObsidianExportError(f"{label}: missing Obsidian backlink")
    if "## Source References" not in content:
        raise ObsidianExportError(f"{label}: missing source references section")
    lowered = content.lower()
    if "raw_json" in lowered or "raw_posts" in lowered:
        raise ObsidianExportError(f"{label}: raw Telegram storage details leaked into vault note")


def _dashboard_note(week_label: str, threads: list[dict], report_path: Path) -> tuple[Path, str]:
    body = "\n".join(
        [
            f"- Latest weekly note: {_wiki(f'10-weekly/{week_label}', week_label)}",
            f"- HTML report: {report_path}",
            f"- Idea threads: {len(threads)}",
            "",
            "## Source References",
            f"- {report_path}",
        ]
    )
    return (
        Path("00-dashboard") / "index.md",
        _note(
            note_type="dashboard",
            title="AI Intelligence Dashboard",
            body=body,
            extra_frontmatter={"week_label": week_label},
        ),
    )


def _analysis_line(item: object, *keys: str) -> str:
    if isinstance(item, dict):
        for key in keys:
            value = str(item.get(key) or "").strip()
            if value:
                return value
        values = [str(value).strip() for value in item.values() if str(value).strip()]
        return " - ".join(values[:2])
    return str(item or "").strip()


def _frontier_analysis_markdown(frontier_analysis: dict | None) -> str:
    if not frontier_analysis:
        return "\n".join(
            [
                "## Frontier Analysis",
                "- Pending: run `frontier-analysis --lookback-weeks 12` and regenerate the report.",
            ]
        )
    study = [
        f"- **{_analysis_line(item, 'topic', 'title')}**: {_analysis_line(item, 'reason', 'why_it_matters')}"
        for item in (frontier_analysis.get("study_now") or [])[:5]
    ]
    actions = [
        f"- **{_analysis_line(item, 'title', 'action')}**: {_analysis_line(item, 'next_step', 'success_criterion')}"
        for item in (frontier_analysis.get("actions") or [])[:5]
    ]
    return "\n".join(
        [
            "## Frontier Analysis",
            frontier_analysis.get("executive_brief") or "No executive brief saved.",
            "",
            "### Study Now",
            *(study or ["- No study recommendations saved."]),
            "",
            "### Do Next",
            *(actions or ["- No actions saved."]),
        ]
    )


def _weekly_note(week_label: str, threads: list[dict], report_path: Path, frontier_analysis: dict | None = None) -> tuple[Path, str]:
    thread_links = []
    for thread in threads:
        thread_path = f"20-idea-threads/{thread['slug']}"
        thread_links.append(
            f"- {_wiki(thread_path, thread['title'])} "
            f"({thread['status']}, momentum_30d={thread['momentum_30d']:.2f})"
        )
    if not thread_links:
        thread_links = ["- No idea threads exported yet."]
    source_urls = _all_source_urls(threads)
    body = "\n".join(
        [
            f"Backlinks: {_wiki('00-dashboard/index', 'Dashboard')}",
            "",
            f"HTML report: {report_path}",
            "",
            _frontier_analysis_markdown(frontier_analysis),
            "",
            "## Idea Threads",
            *thread_links,
            "",
            _source_refs(source_urls or [str(report_path)]),
        ]
    )
    return (
        Path("10-weekly") / f"{week_label}.md",
        _note(
            note_type="weekly_intelligence",
            title=f"AI Intelligence {week_label}",
            body=body,
            extra_frontmatter={
                "week_label": week_label,
                "thread_count": len(threads),
                "source_count": len(source_urls),
            },
        ),
    )


def _thread_note(week_label: str, thread: dict, report_path: Path) -> tuple[Path, str]:
    atom_urls = [url for atom in thread.get("atoms") or [] for url in atom.get("source_urls") or []]
    claims = thread.get("current_claims") or []
    superseded = thread.get("superseded_claims") or []
    timeline = []
    for atom in reversed(thread.get("atoms") or []):
        timeline.append(
            f"- {str(atom.get('last_seen_at') or '')[:10]}: **{atom.get('atom_type')}** "
            f"{atom.get('claim')} ({', '.join(atom.get('source_urls') or [])})"
        )
    body = "\n".join(
        [
            f"Backlinks: {_wiki(f'10-weekly/{week_label}', week_label)}",
            "",
            f"HTML report section: {report_path}#thread-{thread['slug']}",
            "",
            thread.get("summary") or "",
            "",
            "## Current Claims",
            *(f"- {claim}" for claim in claims[:8]),
            *([] if claims else ["- No current claims."]),
            "",
            "## Superseded or Stale Claims",
            *(f"- {claim}" for claim in superseded[:6]),
            *([] if superseded else ["- None visible."]),
            "",
            "## Timeline",
            *(timeline or ["- No linked source atoms."]),
            "",
            _source_refs(atom_urls),
        ]
    )
    return (
        Path("20-idea-threads") / f"{thread['slug']}.md",
        _note(
            note_type="idea_thread",
            title=thread["title"],
            body=body,
            extra_frontmatter={
                "week_label": week_label,
                "slug": thread["slug"],
                "status": thread["status"],
                "first_seen": thread["first_seen_at"][:10],
                "last_seen": thread["last_seen_at"][:10],
                "momentum_7d": thread["momentum_7d"],
                "momentum_30d": thread["momentum_30d"],
                "momentum_90d": thread["momentum_90d"],
                "channels": thread.get("source_channels") or [],
                "entities": thread.get("key_entities") or [],
                "source_count": len(set(atom_urls)),
            },
        ),
    )


def _term_notes(
    week_label: str,
    threads: list[dict],
    *,
    fields: tuple[str, ...],
    folder: str,
    note_type: str,
    report_path: Path,
) -> list[tuple[Path, str]]:
    term_atoms: dict[str, list[dict]] = {}
    for atom in _all_atoms(threads):
        for field in fields:
            for term in atom.get(field) or []:
                term_atoms.setdefault(term, []).append(atom)
    notes = []
    for term, atoms in sorted(term_atoms.items(), key=lambda item: _slug(item[0])):
        urls = [url for atom in atoms for url in atom.get("source_urls") or []]
        claims = [atom.get("claim") or "" for atom in atoms if atom.get("claim")]
        body = "\n".join(
            [
                f"Backlinks: {_wiki(f'10-weekly/{week_label}', week_label)}",
                "",
                f"HTML report section: {report_path}#tools-models-practices",
                "",
                "## Related Claims",
                *(f"- {claim}" for claim in claims[:10]),
                "",
                _source_refs(urls),
            ]
        )
        notes.append(
            (
                Path(folder) / f"{_slug(term)}.md",
                _note(
                    note_type=note_type,
                    title=term,
                    body=body,
                    extra_frontmatter={
                        "week_label": week_label,
                        "slug": _slug(term),
                        "source_count": len(set(urls)),
                    },
                ),
            )
        )
    return notes


def _channel_notes(week_label: str, threads: list[dict], report_path: Path) -> list[tuple[Path, str]]:
    channel_atoms: dict[str, list[dict]] = {}
    for atom in _all_atoms(threads):
        for url in atom.get("source_urls") or []:
            channel = _source_channel(url)
            channel_atoms.setdefault(channel, []).append(atom)
    notes = []
    for channel, atoms in sorted(channel_atoms.items(), key=lambda item: _slug(item[0])):
        urls = [url for atom in atoms for url in atom.get("source_urls") or []]
        body = "\n".join(
            [
                f"Backlinks: {_wiki(f'10-weekly/{week_label}', week_label)}",
                "",
                f"HTML report section: {report_path}#source-map",
                "",
                "## Cited Claims",
                *(f"- {atom.get('claim')}" for atom in atoms[:12]),
                "",
                _source_refs(urls),
            ]
        )
        notes.append(
            (
                Path("50-channels") / f"{_slug(channel)}.md",
                _note(
                    note_type="channel_profile",
                    title=channel,
                    body=body,
                    extra_frontmatter={
                        "week_label": week_label,
                        "channel": channel,
                        "source_count": len(set(urls)),
                    },
                ),
            )
        )
    return notes


def _source_channel(url: str) -> str:
    match = re.match(r"https?://t\.me/([^/\s]+)", str(url or ""))
    if match:
        return match.group(1)
    host = re.sub(r"^https?://", "", str(url or "")).split("/", maxsplit=1)[0]
    return host or "unknown"


def _read_queue_notes(week_label: str, threads: list[dict], report_path: Path) -> list[tuple[Path, str]]:
    notes = []
    read_types = {"tutorial_resource", "case_study", "research_claim", "benchmark_claim"}
    for atom in _all_atoms(threads):
        if atom.get("atom_type") not in read_types:
            continue
        title = atom.get("claim") or f"Read queue atom {atom['id']}"
        urls = atom.get("source_urls") or []
        body = "\n".join(
            [
                f"Backlinks: {_wiki(f'10-weekly/{week_label}', week_label)}",
                "",
                f"HTML report section: {report_path}#read-queue",
                "",
                atom.get("summary") or atom.get("why_it_matters") or "",
                "",
                "## Reading Note",
                "- Read the cited source and record whether it changes an active workflow.",
                "",
                _source_refs(urls),
            ]
        )
        notes.append(
            (
                Path("60-read-queue") / f"{week_label}-{atom['id']}.md",
                _note(
                    note_type="read_queue",
                    title=title,
                    body=body,
                    extra_frontmatter={
                        "week_label": week_label,
                        "atom_id": atom["id"],
                        "atom_type": atom.get("atom_type"),
                        "source_count": len(set(urls)),
                    },
                ),
            )
        )
    return notes


def _experiment_notes(week_label: str, threads: list[dict], report_path: Path) -> list[tuple[Path, str]]:
    ranked = sorted(
        threads,
        key=lambda thread: (
            thread.get("status") == "production_pattern",
            float(thread.get("momentum_30d") or 0.0),
            int(thread.get("source_channel_count") or 0),
        ),
        reverse=True,
    )[:3]
    notes = []
    for thread in ranked:
        urls = [url for atom in thread.get("atoms") or [] for url in atom.get("source_urls") or []]
        weekly_link = _wiki(f"10-weekly/{week_label}", week_label)
        thread_link = _wiki(f"20-idea-threads/{thread['slug']}", thread["title"])
        body = "\n".join(
            [
                f"Backlinks: {weekly_link}, {thread_link}",
                "",
                f"HTML report section: {report_path}#try-this-week",
                "",
                "## Experiment",
                "- Verify one current claim against the cited sources.",
                "- Try one small workflow change for 30 minutes.",
                "- Record whether it should become a repeatable practice.",
                "",
                _source_refs(urls),
            ]
        )
        notes.append(
            (
                Path("70-experiments") / f"{week_label}-{thread['slug']}.md",
                _note(
                    note_type="experiment",
                    title=f"Try: {thread['title']}",
                    body=body,
                    extra_frontmatter={
                        "week_label": week_label,
                        "thread_slug": thread["slug"],
                        "status": "planned",
                        "source_count": len(set(urls)),
                    },
                ),
            )
        )
    return notes


def _manifest(root: Path, week_label: str, files: list[Path], summary: dict) -> None:
    manifest_path = root / "90-generated" / f"export-manifest-{week_label}.json"
    manifest_path.parent.mkdir(parents=True, exist_ok=True)
    payload = {
        "week_label": week_label,
        "generated_at": _utc_now_iso(),
        "generated_from": "telegram-research-agent",
        "files": [str(path.relative_to(root)) for path in files],
        **summary,
    }
    manifest_path.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")


def export_obsidian_vault(
    settings: Settings,
    *,
    week_label: str | None = None,
    vault_path: str | Path | None = None,
    namespace: str | None = None,
    report_root: str | Path | None = None,
    threads_limit: int = 100,
    atoms_limit: int = 20,
) -> ObsidianExportSummary:
    clean_week = str(week_label or _current_week_label()).strip()
    root = _vault_root(vault_path, namespace)
    report_path = _report_path_for_week(clean_week, report_root)
    with sqlite3.connect(settings.db_path) as connection:
        connection.row_factory = sqlite3.Row
        context = load_ai_intelligence_context(
            connection,
            week_label=clean_week,
            threads_limit=threads_limit,
            atoms_limit=atoms_limit,
        )
    threads = context.get("threads") or []
    notes: list[tuple[Path, str]] = [
        _dashboard_note(clean_week, threads, report_path),
        _weekly_note(clean_week, threads, report_path, context.get("frontier_analysis")),
    ]
    notes.extend(_thread_note(clean_week, thread, report_path) for thread in threads)
    notes.extend(
        _term_notes(
            clean_week,
            threads,
            fields=("tools", "models"),
            folder="30-tools-models",
            note_type="tool_model",
            report_path=report_path,
        )
    )
    notes.extend(
        _term_notes(
            clean_week,
            threads,
            fields=("practices",),
            folder="40-practices",
            note_type="engineering_practice",
            report_path=report_path,
        )
    )
    notes.extend(_channel_notes(clean_week, threads, report_path))
    notes.extend(_read_queue_notes(clean_week, threads, report_path))
    notes.extend(_experiment_notes(clean_week, threads, report_path))

    written: list[Path] = []
    for relative_path, content in notes:
        target = root / relative_path
        _write_generated_note(target, content)
        written.append(target)

    atoms = _all_atoms(threads)
    tool_model_terms = {
        term
        for atom in atoms
        for term in [*(atom.get("tools") or []), *(atom.get("models") or [])]
    }
    practice_terms = {term for atom in atoms for term in atom.get("practices") or []}
    channel_terms = {_source_channel(url) for url in _all_source_urls(threads)}
    read_count = len([atom for atom in atoms if atom.get("atom_type") in {"tutorial_resource", "case_study", "research_claim", "benchmark_claim"}])
    experiment_count = min(3, len(threads))
    summary = ObsidianExportSummary(
        week_label=clean_week,
        vault_root=str(root),
        files_written=len(written),
        thread_count=len(threads),
        source_atom_count=len(atoms),
        term_note_count=len(tool_model_terms) + len(practice_terms),
        channel_note_count=len(channel_terms),
        read_queue_note_count=read_count,
        experiment_note_count=experiment_count,
    )
    _manifest(root, clean_week, written, summary.__dict__)
    return summary
