import json
import os
import re
import sqlite3
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path

from config.settings import PROJECT_ROOT, Settings
from db.ai_report_feedback import summarize_ai_report_feedback
from output.ai_intelligence_report import (
    OUTPUT_DIR as AI_REPORT_OUTPUT_DIR,
    _current_week_label,
    load_ai_intelligence_context,
)
from output.ai_report_contract import build_weekly_ai_report_contract
from output.ai_visual_report import _load_projects, _project_links
from output.strategy_reviewer import build_strategy_review


DEFAULT_VAULT_PATH = PROJECT_ROOT / "data" / "output" / "ai_intelligence_vault"
GENERATED_MARKER = "<!-- generated by telegram-research-agent:ai-intelligence -->"
MAX_WEEKLY_THREAD_LINKS = 5
MAX_THREAD_NOTES = 12
MAX_TERM_NOTES_PER_FOLDER = 8
MAX_CHANNEL_NOTES = 8
MAX_READ_QUEUE_NOTES = 5
MAX_EXPERIMENT_NOTES = 1
CURRENT_ATOM_STATUSES = {"", "active"}
PROMOTED_THREAD_STATUSES = {"production_pattern"}
READ_QUEUE_TYPES = {"tutorial_resource", "case_study", "research_claim", "benchmark_claim"}


@dataclass(frozen=True)
class ObsidianExportSummary:
    week_label: str
    vault_root: str
    files_written: int
    thread_count: int
    source_atom_count: int
    term_note_count: int
    channel_note_count: int
    read_queue_note_count: int
    experiment_note_count: int
    try_build_note_count: int
    project_watch_note_count: int
    feedback_summary_note_count: int
    strategy_review_note_count: int


class ObsidianExportError(ValueError):
    pass


def _utc_now_iso() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")


def _slug(value: object) -> str:
    text = str(value or "").strip().lower()
    text = re.sub(r"[^a-z0-9]+", "-", text).strip("-")
    return text or "untitled"


def _vault_root(vault_path: str | Path | None, namespace: str | None) -> Path:
    raw_root = Path(vault_path or os.environ.get("AI_INTELLIGENCE_VAULT_PATH", "") or DEFAULT_VAULT_PATH)
    root = raw_root.expanduser()
    ns = str(namespace or "").strip().strip("/")
    if not ns:
        return root
    ns_path = Path(ns)
    if ns_path.is_absolute() or any(part == ".." for part in ns_path.parts):
        raise ObsidianExportError("namespace must be a relative path without '..'")
    return root / ns_path


def _json_array(values: list | tuple) -> str:
    return json.dumps(list(values), ensure_ascii=False)


def _frontmatter(fields: dict[str, object]) -> str:
    lines = ["---"]
    for key, value in fields.items():
        if isinstance(value, (list, tuple)):
            rendered = _json_array(value)
        elif isinstance(value, bool):
            rendered = "true" if value else "false"
        elif value is None:
            rendered = "null"
        elif isinstance(value, (int, float)):
            rendered = str(value)
        else:
            rendered = json.dumps(str(value), ensure_ascii=False)
        lines.append(f"{key}: {rendered}")
    lines.append("---")
    return "\n".join(lines)


def _note(
    *,
    note_type: str,
    title: str,
    body: str,
    extra_frontmatter: dict[str, object] | None = None,
) -> str:
    frontmatter = {
        "type": note_type,
        "title": title,
        "generated": True,
        "generated_from": "telegram-research-agent",
        "generated_at": _utc_now_iso(),
    }
    frontmatter.update(extra_frontmatter or {})
    return f"{_frontmatter(frontmatter)}\n{GENERATED_MARKER}\n\n# {title}\n\n{body.rstrip()}\n"


def _wiki(path_without_suffix: str, label: str | None = None) -> str:
    clean = path_without_suffix.strip("/")
    if label:
        return f"[[{clean}|{label}]]"
    return f"[[{clean}]]"


def _source_refs(urls: list[str], *, fallback: str = "No source references available yet.") -> str:
    unique = []
    for url in urls:
        clean = str(url or "").strip()
        if clean and clean not in unique:
            unique.append(clean)
    lines = ["## Source References"]
    if unique:
        lines.extend(f"- {url}" for url in unique)
    else:
        lines.append(f"- {fallback}")
    return "\n".join(lines)


def _all_atoms(threads: list[dict]) -> list[dict]:
    atoms = []
    seen = set()
    for thread in threads:
        for atom in thread.get("atoms") or []:
            if atom["id"] in seen:
                continue
            seen.add(atom["id"])
            atoms.append(atom)
    return atoms


def _all_source_urls(threads: list[dict]) -> list[str]:
    return [url for atom in _all_atoms(threads) for url in atom.get("source_urls") or []]


def _atom_id(atom: dict) -> int:
    try:
        return int(atom.get("id") or 0)
    except (TypeError, ValueError):
        return 0


def _thread_atom_ids(thread: dict) -> set[int]:
    return {_atom_id(atom) for atom in thread.get("atoms") or [] if _atom_id(atom)}


def _contract_atom_ids(report_contract: dict) -> set[int]:
    ids: set[int] = set()
    for section in ("decision_cards", "claim_cards"):
        for card in report_contract.get(section) or []:
            if not isinstance(card, dict):
                continue
            if section == "claim_cards" and not (
                bool(card.get("decision_eligible"))
                or bool(card.get("quote_verified"))
                or str(card.get("evidence_tier") or "").startswith("verified")
            ):
                continue
            for value in card.get("evidence_atom_ids") or []:
                try:
                    atom_id = int(value)
                except (TypeError, ValueError):
                    continue
                if atom_id:
                    ids.add(atom_id)
    return ids


def _project_threads(report_contract: dict) -> set[str]:
    slugs: set[str] = set()
    diagnostic = report_contract.get("project_diagnostic") or {}
    for key in ("confirmed_leads", "project_watch"):
        for item in diagnostic.get(key) or []:
            if not isinstance(item, dict):
                continue
            confidence = str(item.get("confidence") or "")
            if key == "project_watch" and confidence not in {"medium", "higher"}:
                continue
            slug = str(item.get("thread_slug") or "").strip()
            if slug:
                slugs.add(slug)
    return slugs


def _eligible_project_watch(report_contract: dict) -> list[dict]:
    diagnostic = report_contract.get("project_diagnostic") or {}
    items: list[dict] = []
    for key in ("confirmed_leads", "project_watch"):
        for item in diagnostic.get(key) or []:
            if not isinstance(item, dict):
                continue
            confidence = str(item.get("confidence") or "")
            evidence_urls = [url for url in item.get("evidence_urls") or [] if str(url).strip()]
            if key == "confirmed_leads":
                if confidence != "higher" or len(evidence_urls) < 2:
                    continue
            elif confidence not in {"medium", "higher"}:
                continue
            items.append({**item, "watch_tier": "confirmed" if key == "confirmed_leads" else "watch"})
    return items[:4]


def _action_text_terms(report_contract: dict) -> set[str]:
    terms: set[str] = set()
    for action in report_contract.get("action_cards") or []:
        if not isinstance(action, dict):
            continue
        text = " ".join(
            str(action.get(key) or "")
            for key in ("title", "next_step", "success_criterion", "scope")
        )
        terms.update(re.findall(r"\b[a-zA-Z][a-zA-Z0-9_-]{2,}\b", text.lower()))
    for item in _eligible_project_watch(report_contract):
        for term in item.get("shared_terms") or []:
            clean = str(term or "").strip().lower()
            if clean:
                terms.add(clean)
    return terms


def _atom_is_current(atom: dict) -> bool:
    return str(atom.get("staleness_status") or "active") in CURRENT_ATOM_STATUSES


def _atom_is_high_signal(atom: dict) -> bool:
    return (
        float(atom.get("practical_utility_score") or 0.0) >= 0.75
        or float(atom.get("novelty_score") or 0.0) >= 0.75
        or float(atom.get("confidence") or 0.0) >= 0.8
    )


def _thread_eligibility_reasons(thread: dict, report_contract: dict) -> list[str]:
    reasons: list[str] = []
    atom_ids = _thread_atom_ids(thread)
    if atom_ids & _contract_atom_ids(report_contract) or str(thread.get("slug") or "") in _project_threads(report_contract):
        reasons.append("decision_relevant")
    if str(thread.get("status") or "") in PROMOTED_THREAD_STATUSES:
        reasons.append("promoted")
    if int(thread.get("atom_count") or len(thread.get("atoms") or [])) >= 2 or int(thread.get("source_channel_count") or 0) >= 2:
        reasons.append("repeated")
    if (
        str(thread.get("status") or "") in {"active", "production_pattern"}
        and bool(thread.get("changed_this_week"))
        and any(_atom_is_current(atom) and _atom_is_high_signal(atom) for atom in thread.get("atoms") or [])
    ):
        reasons.append("active")
    return list(dict.fromkeys(reasons))


def _thread_score(thread: dict, report_contract: dict) -> tuple[int, int, int, int, float, int, int, str]:
    reasons = set(_thread_eligibility_reasons(thread, report_contract))
    return (
        int("decision_relevant" in reasons),
        int("promoted" in reasons),
        int("repeated" in reasons),
        int("active" in reasons),
        float(thread.get("momentum_30d") or 0.0),
        int(thread.get("source_channel_count") or 0),
        int(thread.get("atom_count") or len(thread.get("atoms") or [])),
        str(thread.get("last_seen_at") or ""),
    )


def _selected_threads(threads: list[dict], report_contract: dict) -> list[dict]:
    eligible = [thread for thread in threads if _thread_eligibility_reasons(thread, report_contract)]
    eligible.sort(key=lambda thread: _thread_score(thread, report_contract), reverse=True)
    return eligible[:MAX_THREAD_NOTES]


def _weekly_threads(threads: list[dict], report_contract: dict) -> list[dict]:
    selected = list(threads)
    selected.sort(key=lambda thread: _thread_score(thread, report_contract), reverse=True)
    return [thread for thread in selected if _thread_score(thread, report_contract)[0:4] != (0, 0, 0, 0)][:MAX_WEEKLY_THREAD_LINKS]


def _projection_context(context: dict) -> dict:
    projects = _load_projects()
    project_links = _project_links(context, projects)
    report_contract = build_weekly_ai_report_contract(
        context,
        project_links=project_links,
        projects=projects,
    )
    threads = [thread for thread in context.get("threads") or [] if isinstance(thread, dict)]
    exported_threads = _selected_threads(threads, report_contract)
    return {
        "report_contract": report_contract,
        "project_links": project_links,
        "projects": projects,
        "all_threads": threads,
        "exported_threads": exported_threads,
        "weekly_threads": _weekly_threads(threads, report_contract),
        "read_atoms": _eligible_read_queue_atoms(threads, report_contract),
        "try_actions": [
            action
            for action in report_contract.get("action_cards") or []
            if isinstance(action, dict) and action.get("action_kind") == "try"
        ][:2],
        "experiment_actions": [
            action
            for action in report_contract.get("action_cards") or []
            if isinstance(action, dict) and action.get("action_kind") == "experiment"
        ][:MAX_EXPERIMENT_NOTES],
        "project_watch": _eligible_project_watch(report_contract),
        "build_suggestions": [
            suggestion
            for suggestion in ((report_contract.get("project_diagnostic") or {}).get("implementation_suggestions") or [])
            if isinstance(suggestion, dict)
        ][:4],
    }


def _report_path_for_week(week_label: str, report_root: str | Path | None) -> Path:
    root = Path(report_root) if report_root is not None else AI_REPORT_OUTPUT_DIR
    return root / f"{week_label}.html"


def _write_generated_note(path: Path, content: str) -> None:
    if path.exists():
        existing = path.read_text(encoding="utf-8")
        if GENERATED_MARKER not in existing:
            raise ObsidianExportError(f"refusing to overwrite hand-authored note: {path}")
    validate_generated_markdown(content, path=path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def validate_generated_markdown(content: str, *, path: Path | None = None) -> None:
    label = str(path) if path else "generated note"
    if not content.startswith("---\n"):
        raise ObsidianExportError(f"{label}: missing frontmatter")
    if GENERATED_MARKER not in content:
        raise ObsidianExportError(f"{label}: missing generated marker")
    if "[[" not in content:
        raise ObsidianExportError(f"{label}: missing Obsidian backlink")
    if "## Source References" not in content:
        raise ObsidianExportError(f"{label}: missing source references section")
    lowered = content.lower()
    if "raw_json" in lowered or "raw_posts" in lowered:
        raise ObsidianExportError(f"{label}: raw Telegram storage details leaked into vault note")


def _dashboard_note(week_label: str, threads: list[dict], report_path: Path) -> tuple[Path, str]:
    body = "\n".join(
        [
            f"- Latest weekly note: {_wiki(f'10-weekly/{week_label}', week_label)}",
            f"- HTML report: {report_path}",
            f"- Idea threads: {len(threads)}",
            "",
            "## Source References",
            f"- {report_path}",
        ]
    )
    return (
        Path("00-dashboard") / "index.md",
        _note(
            note_type="dashboard",
            title="AI Intelligence Dashboard",
            body=body,
            extra_frontmatter={"week_label": week_label},
        ),
    )


def _analysis_line(item: object, *keys: str) -> str:
    if isinstance(item, dict):
        for key in keys:
            value = str(item.get(key) or "").strip()
            if value:
                return value
        values = [str(value).strip() for value in item.values() if str(value).strip()]
        return " - ".join(values[:2])
    return str(item or "").strip()


def _frontier_analysis_markdown(frontier_analysis: dict | None) -> str:
    if not frontier_analysis:
        return "\n".join(
            [
                "## Frontier Analysis",
                "- Pending: run `frontier-analysis --lookback-weeks 12` and regenerate the report.",
            ]
        )
    study = [
        f"- **{_analysis_line(item, 'topic', 'title')}**: {_analysis_line(item, 'reason', 'why_it_matters')}"
        for item in (frontier_analysis.get("study_now") or [])[:5]
    ]
    actions = [
        f"- **{_analysis_line(item, 'title', 'action')}**: {_analysis_line(item, 'next_step', 'success_criterion')}"
        for item in (frontier_analysis.get("actions") or [])[:5]
    ]
    return "\n".join(
        [
            "## Frontier Analysis",
            frontier_analysis.get("executive_brief") or "No executive brief saved.",
            "",
            "### Study Now",
            *(study or ["- No study recommendations saved."]),
            "",
            "### Do Next",
            *(actions or ["- No actions saved."]),
        ]
    )


def _read_queue_note_path(week_label: str, atom: dict) -> str:
    return f"60-read-queue/{week_label}-{atom['id']}"


def _experiment_note_path(week_label: str, action: dict) -> str:
    return f"70-experiments/{week_label}-{_slug(action.get('id') or action.get('target_ref') or 'experiment')}"


def _try_build_note_path(week_label: str) -> str:
    return f"65-try-build/{week_label}-try-build"


def _project_watch_note_path(week_label: str) -> str:
    return f"75-project-watch/{week_label}-project-watch"


def _feedback_summary_note_path(week_label: str) -> str:
    return f"80-feedback/{week_label}-feedback-summary"


def _strategy_review_note_path(week_label: str) -> str:
    return f"85-strategy/{week_label}-strategy-review"


def _weekly_note(
    week_label: str,
    threads: list[dict],
    report_path: Path,
    frontier_analysis: dict | None = None,
    projection: dict | None = None,
) -> tuple[Path, str]:
    projection = projection or {}
    weekly_threads = projection.get("weekly_threads") or threads[:MAX_WEEKLY_THREAD_LINKS]
    thread_links = []
    for thread in weekly_threads:
        thread_path = f"20-idea-threads/{thread['slug']}"
        thread_links.append(
            f"- {_wiki(thread_path, thread['title'])} "
            f"({thread['status']}, momentum_30d={thread['momentum_30d']:.2f})"
        )
    if not thread_links:
        thread_links = ["- No idea threads exported yet."]
    read_links = []
    for atom in projection.get("read_atoms") or []:
        title = atom.get("claim") or f"Read queue atom {atom.get('id')}"
        read_links.append(f"- {_wiki(_read_queue_note_path(week_label, atom), title)}")
    if not read_links:
        read_links = ["- No read queue items passed the export threshold."]

    try_links = []
    for action in projection.get("try_actions") or []:
        target = str(action.get("target_ref") or action.get("id") or "try")
        try_links.append(
            f"- `{target}`: {action.get('title') or 'Try item'} "
            f"({action.get('effort') or 'effort n/a'}; feedback={action.get('feedback_target_id') or 'n/a'})"
        )
    if not try_links:
        try_links = ["- No try items passed the report contract threshold."]

    build_links = [f"- {_wiki(_try_build_note_path(week_label), 'Try / Build candidates')}"]
    for suggestion in projection.get("build_suggestions") or []:
        build_links.append(
            f"- `{suggestion.get('target_ref') or suggestion.get('id') or 'build'}`: "
            f"{suggestion.get('title') or suggestion.get('next_step') or 'Build candidate'}"
        )
    if len(build_links) == 1:
        build_links.append("- No build candidate passed the project diagnostic threshold.")

    experiment_links = []
    for action in projection.get("experiment_actions") or []:
        title = action.get("title") or "Weekly experiment"
        experiment_links.append(f"- {_wiki(_experiment_note_path(week_label, action), title)}")
    if not experiment_links:
        experiment_links = ["- No experiment action passed the report contract threshold."]

    project_watch_links = [f"- {_wiki(_project_watch_note_path(week_label), 'Project watch')}"]
    for item in projection.get("project_watch") or []:
        thread_slug = str(item.get("thread_slug") or "").strip()
        thread_title = str(item.get("thread_title") or thread_slug or "thread").strip()
        thread_ref = _wiki(f"20-idea-threads/{thread_slug}", thread_title) if thread_slug else thread_title
        project_watch_links.append(
            f"- **{item.get('project') or 'project'}** -> {thread_ref} "
            f"({item.get('watch_tier') or 'watch'}, confidence={item.get('confidence') or 'n/a'})"
        )
    if len(project_watch_links) == 1:
        project_watch_links.append("- No project watch items passed the evidence threshold.")

    feedback_links = [
        f"- {_wiki(_feedback_summary_note_path(week_label), 'Feedback summary')}",
        f"- {_wiki(_strategy_review_note_path(week_label), 'Strategy Reviewer')}",
    ]

    source_urls = _all_source_urls(threads)
    body = "\n".join(
        [
            f"Backlinks: {_wiki('00-dashboard/index', 'Dashboard')}",
            "",
            f"HTML report: {report_path}",
            "",
            _frontier_analysis_markdown(frontier_analysis),
            "",
            "## Idea Threads",
            *thread_links,
            "",
            "## Read Queue",
            *read_links,
            "",
            "## Try Items",
            *try_links,
            "",
            "## Build Candidates",
            *build_links,
            "",
            "## Experiment",
            *experiment_links,
            "",
            "## Project Watch",
            *project_watch_links,
            "",
            "## Feedback And Strategy",
            *feedback_links,
            "",
            "## Manual Promotion",
            "- Promote mature insights by hand after source review; this generated note remains disposable.",
            "",
            _source_refs(source_urls or [str(report_path)]),
        ]
    )
    return (
        Path("10-weekly") / f"{week_label}.md",
        _note(
            note_type="weekly_intelligence",
            title=f"AI Intelligence {week_label}",
            body=body,
            extra_frontmatter={
                "week_label": week_label,
                "thread_count": len(threads),
                "source_count": len(source_urls),
            },
        ),
    )


def _thread_note(week_label: str, thread: dict, report_path: Path) -> tuple[Path, str]:
    atom_urls = [url for atom in thread.get("atoms") or [] for url in atom.get("source_urls") or []]
    claims = thread.get("current_claims") or []
    superseded = thread.get("superseded_claims") or []
    timeline = []
    for atom in reversed(thread.get("atoms") or []):
        timeline.append(
            f"- {str(atom.get('last_seen_at') or '')[:10]}: **{atom.get('atom_type')}** "
            f"{atom.get('claim')} ({', '.join(atom.get('source_urls') or [])})"
        )
    body = "\n".join(
        [
            f"Backlinks: {_wiki(f'10-weekly/{week_label}', week_label)}",
            "",
            f"HTML report section: {report_path}#thread-{thread['slug']}",
            "",
            thread.get("summary") or "",
            "",
            "## Current Claims",
            *(f"- {claim}" for claim in claims[:8]),
            *([] if claims else ["- No current claims."]),
            "",
            "## Superseded or Stale Claims",
            *(f"- {claim}" for claim in superseded[:6]),
            *([] if superseded else ["- None visible."]),
            "",
            "## Timeline",
            *(timeline or ["- No linked source atoms."]),
            "",
            "## Manual Promotion",
            "- Promote only after the source references and current decision have been reviewed by hand.",
            "",
            _source_refs(atom_urls),
        ]
    )
    return (
        Path("20-idea-threads") / f"{thread['slug']}.md",
        _note(
            note_type="idea_thread",
            title=thread["title"],
            body=body,
            extra_frontmatter={
                "week_label": week_label,
                "slug": thread["slug"],
                "status": thread["status"],
                "first_seen": thread["first_seen_at"][:10],
                "last_seen": thread["last_seen_at"][:10],
                "momentum_7d": thread["momentum_7d"],
                "momentum_30d": thread["momentum_30d"],
                "momentum_90d": thread["momentum_90d"],
                "channels": thread.get("source_channels") or [],
                "entities": thread.get("key_entities") or [],
                "source_count": len(set(atom_urls)),
            },
        ),
    )


def _term_notes(
    week_label: str,
    threads: list[dict],
    *,
    fields: tuple[str, ...],
    folder: str,
    note_type: str,
    report_path: Path,
    report_contract: dict | None = None,
) -> list[tuple[Path, str]]:
    report_contract = report_contract or {}
    term_atoms: dict[str, list[dict]] = {}
    term_threads: dict[str, list[dict]] = {}
    for atom in _all_atoms(threads):
        for field in fields:
            for term in atom.get(field) or []:
                term_atoms.setdefault(term, []).append(atom)
    for thread in threads:
        for atom in thread.get("atoms") or []:
            for field in fields:
                for term in atom.get(field) or []:
                    term_threads.setdefault(term, []).append(thread)
    notes = []
    candidates = []
    for term, atoms in term_atoms.items():
        reasons = _term_eligibility_reasons(
            term,
            atoms,
            term_threads.get(term) or [],
            report_contract,
        )
        if not reasons:
            continue
        candidates.append((term, atoms, reasons))
    candidates.sort(
        key=lambda item: (
            int("decision_relevant" in item[2]),
            int("promoted" in item[2]),
            int("repeated" in item[2]),
            int("active" in item[2]),
            len({_atom_id(atom) for atom in item[1] if _atom_id(atom)}),
            _slug(item[0]),
        ),
        reverse=True,
    )
    for term, atoms, reasons in candidates[:MAX_TERM_NOTES_PER_FOLDER]:
        urls = [url for atom in atoms for url in atom.get("source_urls") or []]
        claims = [atom.get("claim") or "" for atom in atoms if atom.get("claim")]
        body = "\n".join(
            [
                f"Backlinks: {_wiki(f'10-weekly/{week_label}', week_label)}",
                "",
                f"HTML report section: {report_path}#tools-models-practices",
                "",
                f"Eligibility: {', '.join(reasons)}",
                "",
                "## Related Claims",
                *(f"- {claim}" for claim in claims[:10]),
                "",
                "## Manual Promotion",
                "- Promote into hand-authored notes only after the repeated signal changes a real workflow or decision.",
                "",
                _source_refs(urls),
            ]
        )
        notes.append(
            (
                Path(folder) / f"{_slug(term)}.md",
                _note(
                    note_type=note_type,
                    title=term,
                    body=body,
                    extra_frontmatter={
                        "week_label": week_label,
                        "slug": _slug(term),
                        "source_count": len(set(urls)),
                        "atom_count": len({_atom_id(atom) for atom in atoms if _atom_id(atom)}),
                        "eligibility_reasons": reasons,
                    },
                ),
            )
        )
    return notes


def _term_eligibility_reasons(term: str, atoms: list[dict], threads: list[dict], report_contract: dict) -> list[str]:
    reasons: list[str] = []
    atom_ids = {_atom_id(atom) for atom in atoms if _atom_id(atom)}
    channels = {_source_channel(url) for atom in atoms for url in atom.get("source_urls") or []}
    if atom_ids & _contract_atom_ids(report_contract) or _term_matches_action(term, _action_text_terms(report_contract)):
        reasons.append("decision_relevant")
    if any(str(thread.get("status") or "") in PROMOTED_THREAD_STATUSES for thread in threads):
        reasons.append("promoted")
    if len(atom_ids) >= 2 or len(channels) >= 2:
        reasons.append("repeated")
    if any(_atom_is_current(atom) and _atom_is_high_signal(atom) for atom in atoms):
        reasons.append("active")
    return reasons


def _term_matches_action(term: str, action_terms: set[str]) -> bool:
    clean = " ".join(str(term or "").strip().lower().split())
    if not clean:
        return False
    slug = _slug(clean)
    if clean in action_terms or slug in action_terms:
        return True
    return any(token in action_terms for token in re.findall(r"\b[a-zA-Z][a-zA-Z0-9_-]{2,}\b", clean))


def _channel_notes(
    week_label: str,
    threads: list[dict],
    report_path: Path,
    *,
    report_contract: dict | None = None,
) -> list[tuple[Path, str]]:
    report_contract = report_contract or {}
    channel_atoms: dict[str, list[dict]] = {}
    channel_threads: dict[str, list[dict]] = {}
    for atom in _all_atoms(threads):
        for url in atom.get("source_urls") or []:
            channel = _source_channel(url)
            channel_atoms.setdefault(channel, []).append(atom)
    for thread in threads:
        for atom in thread.get("atoms") or []:
            for url in atom.get("source_urls") or []:
                channel_threads.setdefault(_source_channel(url), []).append(thread)
    notes = []
    candidates = []
    for channel, atoms in channel_atoms.items():
        reasons = _channel_eligibility_reasons(
            atoms,
            channel_threads.get(channel) or [],
            report_contract,
        )
        if not reasons:
            continue
        candidates.append((channel, atoms, reasons))
    candidates.sort(
        key=lambda item: (
            int("decision_relevant" in item[2]),
            int("promoted" in item[2]),
            int("repeated" in item[2]),
            int("active" in item[2]),
            len({_atom_id(atom) for atom in item[1] if _atom_id(atom)}),
            _slug(item[0]),
        ),
        reverse=True,
    )
    for channel, atoms, reasons in candidates[:MAX_CHANNEL_NOTES]:
        urls = [url for atom in atoms for url in atom.get("source_urls") or []]
        body = "\n".join(
            [
                f"Backlinks: {_wiki(f'10-weekly/{week_label}', week_label)}",
                "",
                f"HTML report section: {report_path}#source-map",
                "",
                f"Eligibility: {', '.join(reasons)}",
                "",
                "## Cited Claims",
                *(f"- {atom.get('claim')}" for atom in atoms[:12]),
                "",
                "## Manual Promotion",
                "- Promote the channel profile manually only when repeated evidence shows durable source value.",
                "",
                _source_refs(urls),
            ]
        )
        notes.append(
            (
                Path("50-channels") / f"{_slug(channel)}.md",
                _note(
                    note_type="channel_profile",
                    title=channel,
                    body=body,
                    extra_frontmatter={
                        "week_label": week_label,
                        "channel": channel,
                        "source_count": len(set(urls)),
                        "atom_count": len({_atom_id(atom) for atom in atoms if _atom_id(atom)}),
                        "eligibility_reasons": reasons,
                    },
                ),
            )
        )
    return notes


def _channel_eligibility_reasons(atoms: list[dict], threads: list[dict], report_contract: dict) -> list[str]:
    reasons: list[str] = []
    atom_ids = {_atom_id(atom) for atom in atoms if _atom_id(atom)}
    if atom_ids & _contract_atom_ids(report_contract):
        reasons.append("decision_relevant")
    if any(str(thread.get("status") or "") in PROMOTED_THREAD_STATUSES for thread in threads):
        reasons.append("promoted")
    if len(atom_ids) >= 2:
        reasons.append("repeated")
    if any(_atom_is_current(atom) and _atom_is_high_signal(atom) for atom in atoms):
        reasons.append("active")
    return reasons


def _source_channel(url: str) -> str:
    match = re.match(r"https?://t\.me/([^/\s]+)", str(url or ""))
    if match:
        return match.group(1)
    host = re.sub(r"^https?://", "", str(url or "")).split("/", maxsplit=1)[0]
    return host or "unknown"


def _eligible_read_queue_atoms(threads: list[dict], report_contract: dict | None = None) -> list[dict]:
    report_contract = report_contract or {}
    decision_atom_ids = _contract_atom_ids(report_contract)
    atoms = []
    seen: set[int] = set()
    for atom in _all_atoms(threads):
        atom_id = _atom_id(atom)
        if not atom_id or atom_id in seen:
            continue
        seen.add(atom_id)
        if atom.get("atom_type") not in READ_QUEUE_TYPES:
            continue
        if not atom.get("source_urls"):
            continue
        if not (
            atom_id in decision_atom_ids
            or (_atom_is_current(atom) and _atom_is_high_signal(atom))
        ):
            continue
        atoms.append(atom)
    atoms.sort(
        key=lambda atom: (
            int(_atom_id(atom) in decision_atom_ids),
            float(atom.get("practical_utility_score") or 0.0),
            float(atom.get("novelty_score") or 0.0),
            float(atom.get("confidence") or 0.0),
            str(atom.get("last_seen_at") or ""),
        ),
        reverse=True,
    )
    return atoms[:MAX_READ_QUEUE_NOTES]


def _read_queue_notes(
    week_label: str,
    threads: list[dict],
    report_path: Path,
    *,
    read_atoms: list[dict] | None = None,
    report_contract: dict | None = None,
) -> list[tuple[Path, str]]:
    notes = []
    selected_atoms = read_atoms if read_atoms is not None else _eligible_read_queue_atoms(threads, report_contract)
    for atom in selected_atoms:
        title = atom.get("claim") or f"Read queue atom {atom['id']}"
        urls = atom.get("source_urls") or []
        body = "\n".join(
            [
                f"Backlinks: {_wiki(f'10-weekly/{week_label}', week_label)}",
                "",
                f"HTML report section: {report_path}#read-queue",
                "",
                atom.get("summary") or atom.get("why_it_matters") or "",
                "",
                "## Reading Note",
                "- Read the cited source and record whether it changes an active workflow.",
                "- If useful, promote the distilled lesson manually into the hand-authored cognition vault.",
                "",
                _source_refs(urls),
            ]
        )
        notes.append(
            (
                Path("60-read-queue") / f"{week_label}-{atom['id']}.md",
                _note(
                    note_type="read_queue",
                    title=title,
                    body=body,
                    extra_frontmatter={
                        "week_label": week_label,
                        "atom_id": atom["id"],
                        "atom_type": atom.get("atom_type"),
                        "source_count": len(set(urls)),
                    },
                ),
            )
        )
    return notes


def _try_build_note(
    week_label: str,
    report_path: Path,
    *,
    try_actions: list[dict],
    build_suggestions: list[dict],
    threads: list[dict],
) -> tuple[Path, str]:
    try_lines = [
        f"- **{action.get('title') or action.get('target_ref') or 'Try item'}**: "
        f"{action.get('next_step') or 'Run the bounded try step.'} "
        f"(feedback={action.get('feedback_target_id') or 'n/a'})"
        for action in try_actions
    ] or ["- No try item passed the report contract threshold."]
    build_lines = []
    for suggestion in build_suggestions:
        build_lines.append(
            f"- **{suggestion.get('title') or suggestion.get('target_ref') or 'Build candidate'}**: "
            f"{suggestion.get('next_step') or 'No next step saved.'} "
            f"(effort={suggestion.get('effort') or 'n/a'})"
        )
        acceptance = suggestion.get("acceptance_criteria") or []
        build_lines.extend(f"  - acceptance: {item}" for item in acceptance[:3])
    if not build_lines:
        build_lines = ["- No build candidate passed the project diagnostic threshold."]
    source_urls = [url for item in build_suggestions for url in item.get("source_urls") or []]
    body = "\n".join(
        [
            f"Backlinks: {_wiki(f'10-weekly/{week_label}', week_label)}",
            "",
            f"HTML report section: {report_path}#actions",
            "",
            "## Try",
            *try_lines,
            "",
            "## Build Candidates",
            *build_lines,
            "",
            "## Guardrail",
            "- Generated build candidates are backlog prompts, not permission to build without human review.",
            "",
            _source_refs(source_urls or _all_source_urls(threads) or [str(report_path)]),
        ]
    )
    return (
        Path("65-try-build") / f"{week_label}-try-build.md",
        _note(
            note_type="try_build",
            title=f"Try / Build {week_label}",
            body=body,
            extra_frontmatter={
                "week_label": week_label,
                "try_count": len(try_actions),
                "build_candidate_count": len(build_suggestions),
            },
        ),
    )


def _experiment_notes(
    week_label: str,
    threads: list[dict],
    report_path: Path,
    *,
    experiment_actions: list[dict] | None = None,
    project_watch: list[dict] | None = None,
) -> list[tuple[Path, str]]:
    actions = (experiment_actions or [])[:MAX_EXPERIMENT_NOTES]
    if not actions:
        return []
    thread_by_slug = {str(thread.get("slug") or ""): thread for thread in threads}
    watch_items = project_watch or []
    notes = []
    for action in actions:
        linked_project = watch_items[0] if watch_items else None
        linked_thread = None
        if linked_project:
            linked_thread = thread_by_slug.get(str(linked_project.get("thread_slug") or ""))
        if linked_thread is None and threads:
            linked_thread = sorted(
                threads,
                key=lambda thread: (
                    thread.get("status") == "production_pattern",
                    float(thread.get("momentum_30d") or 0.0),
                    int(thread.get("source_channel_count") or 0),
                ),
                reverse=True,
            )[0]
        thread = linked_thread or {}
        urls = [url for atom in thread.get("atoms") or [] for url in atom.get("source_urls") or []]
        weekly_link = _wiki(f"10-weekly/{week_label}", week_label)
        thread_slug = str(thread.get("slug") or "").strip()
        thread_title = str(thread.get("title") or thread_slug or "No linked thread").strip()
        thread_link = _wiki(f"20-idea-threads/{thread_slug}", thread_title) if thread_slug else "No linked thread"
        project_lines = []
        if linked_project:
            project_lines = [
                f"- Project: **{linked_project.get('project') or 'project'}**",
                f"- Evidence tier: {linked_project.get('watch_tier') or 'watch'} / confidence={linked_project.get('confidence') or 'n/a'}",
                f"- Why: {linked_project.get('why') or 'Project watch item passed threshold.'}",
            ]
        else:
            project_lines = ["- No project link yet. Promote manually only after evidence changes an active project."]
        body = "\n".join(
            [
                f"Backlinks: {weekly_link}, {thread_link}",
                "",
                f"HTML report section: {report_path}#actions",
                "",
                "## Hypothesis",
                f"- {action.get('success_criterion') or 'A small change will create a measurable operator benefit.'}",
                "",
                "## Method",
                f"- {action.get('next_step') or 'Run one bounded experiment against the linked thread.'}",
                f"- Effort: {action.get('effort') or '60 min'}",
                f"- Kill condition: {action.get('kill_condition') or 'Stop if there is no measurable result.'}",
                "",
                "## Result",
                "- Pending. Record observed outcome, source caveats, and feedback event.",
                "",
                "## Decision",
                "- Pending: continue, kill, defer, or promote into a hand-authored cognition note.",
                "",
                "## Project Link",
                *project_lines,
                "",
                "## Manual Promotion",
                "- If the result is useful, move the distilled decision into the hand-authored vault and keep this generated note as trace evidence.",
                "",
                _source_refs(urls or [str(report_path)]),
            ]
        )
        notes.append(
            (
                Path("70-experiments") / f"{week_label}-{_slug(action.get('id') or action.get('target_ref') or 'experiment')}.md",
                _note(
                    note_type="experiment",
                    title=f"Experiment: {action.get('title') or 'Weekly experiment'}",
                    body=body,
                    extra_frontmatter={
                        "week_label": week_label,
                        "action_id": action.get("id"),
                        "feedback_target_id": action.get("feedback_target_id"),
                        "thread_slug": thread_slug,
                        "project": linked_project.get("project") if linked_project else None,
                        "status": "planned",
                        "source_count": len(set(urls)),
                    },
                ),
            )
        )
    return notes


def _project_watch_note(
    week_label: str,
    report_path: Path,
    *,
    project_watch: list[dict],
    threads: list[dict],
) -> tuple[Path, str]:
    lines = []
    for item in project_watch:
        thread_slug = str(item.get("thread_slug") or "").strip()
        thread_title = str(item.get("thread_title") or thread_slug or "thread").strip()
        thread_ref = _wiki(f"20-idea-threads/{thread_slug}", thread_title) if thread_slug else thread_title
        lines.append(
            f"- **{item.get('project') or 'project'}** -> {thread_ref}: "
            f"{item.get('why') or 'Evidence-linked watch item.'} "
            f"(tier={item.get('watch_tier') or 'watch'}, confidence={item.get('confidence') or 'n/a'})"
        )
    if not lines:
        lines = ["- No project watch item passed the evidence threshold."]
    source_urls = [url for item in project_watch for url in item.get("evidence_urls") or []]
    body = "\n".join(
        [
            f"Backlinks: {_wiki(f'10-weekly/{week_label}', week_label)}",
            "",
            f"HTML report section: {report_path}#projects",
            "",
            "## Project Watch",
            *lines,
            "",
            "## Manual Promotion",
            "- Promote into a hand-authored project note only after the watch item changes backlog, code, or an experiment decision.",
            "",
            _source_refs(source_urls or _all_source_urls(threads) or [str(report_path)]),
        ]
    )
    return (
        Path("75-project-watch") / f"{week_label}-project-watch.md",
        _note(
            note_type="project_watch",
            title=f"Project Watch {week_label}",
            body=body,
            extra_frontmatter={
                "week_label": week_label,
                "watch_count": len(project_watch),
            },
        ),
    )


def _feedback_summary_note(week_label: str, report_path: Path, feedback_summary: dict) -> tuple[Path, str]:
    changes = feedback_summary.get("feedback_changes") or {}
    completion = feedback_summary.get("feedback_completion") or {}
    counts = feedback_summary.get("counts_by_feedback") or {}
    count_lines = [f"- {name}: {count}" for name, count in sorted(counts.items())] or ["- No confirmed feedback yet."]
    change_lines = [f"- {item}" for item in changes.get("items") or []] or ["- No feedback-driven changes yet."]
    recent_lines = []
    source_urls = []
    for event in feedback_summary.get("recent_events") or []:
        source_url = str(event.get("source_url") or "").strip()
        if source_url:
            source_urls.append(source_url)
        recent_lines.append(
            f"- {event.get('week_label') or week_label}: {event.get('feedback_type') or 'feedback'} "
            f"on {event.get('target_type') or 'target'}:{event.get('target_ref') or 'n/a'}"
        )
    if not recent_lines:
        recent_lines = ["- No confirmed feedback events exported."]
    body = "\n".join(
        [
            f"Backlinks: {_wiki(f'10-weekly/{week_label}', week_label)}, "
            f"{_wiki(_strategy_review_note_path(week_label), 'Strategy Reviewer')}",
            "",
            f"HTML report section: {report_path}#feedback",
            "",
            "## Completion",
            f"- completed={bool(completion.get('completed'))} "
            f"({completion.get('completed_count') or 0}/{completion.get('required_count') or 0})",
            f"- missing: {', '.join(completion.get('missing') or []) or 'none'}",
            "",
            "## Counts",
            *count_lines,
            "",
            "## What Changed",
            *change_lines,
            "",
            "## Recent Events",
            *recent_lines,
            "",
            "## Manual Promotion",
            "- Keep this as disposable memory; promote only distilled preferences by hand.",
            "",
            _source_refs(source_urls or [str(report_path)]),
        ]
    )
    return (
        Path("80-feedback") / f"{week_label}-feedback-summary.md",
        _note(
            note_type="feedback_summary",
            title=f"Feedback Summary {week_label}",
            body=body,
            extra_frontmatter={
                "week_label": week_label,
                "event_count": int(feedback_summary.get("event_count") or 0),
                "feedback_status": changes.get("status") or "unknown",
            },
        ),
    )


def _strategy_review_note(week_label: str, report_path: Path, strategy_review: dict) -> tuple[Path, str]:
    suggestions = strategy_review.get("suggestions") or {}

    def section_lines(name: str) -> list[str]:
        values = [str(item).strip() for item in suggestions.get(name) or [] if str(item).strip()]
        return [f"- {item}" for item in values] or ["- None."]

    task_lines = []
    for task in strategy_review.get("codex_tasks") or []:
        if not isinstance(task, dict):
            continue
        task_lines.append(f"- **{task.get('title') or 'Task'}**: {task.get('rationale') or 'No rationale saved.'}")
    if not task_lines:
        task_lines = ["- No Codex task suggested."]
    approval_lines = []
    for item in strategy_review.get("approval_required") or []:
        if isinstance(item, dict):
            approval_lines.append(f"- {item.get('change_type') or 'change'}: {item.get('reason') or 'approval required'}")
    if not approval_lines:
        approval_lines = ["- No approval-gated change suggested."]
    body = "\n".join(
        [
            f"Backlinks: {_wiki(f'10-weekly/{week_label}', week_label)}, "
            f"{_wiki(_feedback_summary_note_path(week_label), 'Feedback summary')}",
            "",
            f"HTML report section: {report_path}#feedback",
            "",
            "## Keep",
            *section_lines("keep"),
            "",
            "## Change",
            *section_lines("change"),
            "",
            "## Demote",
            *section_lines("demote"),
            "",
            "## Test Next Week",
            *section_lines("test_next_week"),
            "",
            "## Codex Tasks",
            *task_lines,
            "",
            "## Approval Required",
            *approval_lines,
            "",
            "## Mutation Policy",
            "- Advisory only: no source, prompt, threshold, profile, or project mutation is applied by export.",
            "",
            _source_refs([str(report_path)]),
        ]
    )
    return (
        Path("85-strategy") / f"{week_label}-strategy-review.md",
        _note(
            note_type="strategy_review",
            title=f"Strategy Reviewer {week_label}",
            body=body,
            extra_frontmatter={
                "week_label": week_label,
                "approval_required_count": len(strategy_review.get("approval_required") or []),
                "codex_task_count": len(strategy_review.get("codex_tasks") or []),
            },
        ),
    )


def _manifest(root: Path, week_label: str, files: list[Path], summary: dict) -> None:
    manifest_path = root / "90-generated" / f"export-manifest-{week_label}.json"
    manifest_path.parent.mkdir(parents=True, exist_ok=True)
    payload = {
        "week_label": week_label,
        "generated_at": _utc_now_iso(),
        "generated_from": "telegram-research-agent",
        "files": [str(path.relative_to(root)) for path in files],
        **summary,
    }
    manifest_path.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")


def export_obsidian_vault(
    settings: Settings,
    *,
    week_label: str | None = None,
    vault_path: str | Path | None = None,
    namespace: str | None = None,
    report_root: str | Path | None = None,
    threads_limit: int = 100,
    atoms_limit: int = 20,
) -> ObsidianExportSummary:
    clean_week = str(week_label or _current_week_label()).strip()
    root = _vault_root(vault_path, namespace)
    report_path = _report_path_for_week(clean_week, report_root)
    with sqlite3.connect(settings.db_path) as connection:
        connection.row_factory = sqlite3.Row
        context = load_ai_intelligence_context(
            connection,
            week_label=clean_week,
            threads_limit=threads_limit,
            atoms_limit=atoms_limit,
        )
        feedback_summary = summarize_ai_report_feedback(connection, week_label=clean_week)
        strategy_review = build_strategy_review(connection, week_label=clean_week)
    projection = _projection_context(context)
    all_threads = projection.get("all_threads") or []
    threads = projection.get("exported_threads") or []
    report_contract = projection.get("report_contract") or {}
    notes: list[tuple[Path, str]] = [
        _dashboard_note(clean_week, threads, report_path),
        _weekly_note(
            clean_week,
            all_threads,
            report_path,
            context.get("frontier_analysis"),
            projection=projection,
        ),
    ]
    notes.extend(_thread_note(clean_week, thread, report_path) for thread in threads)
    tool_model_notes = _term_notes(
        clean_week,
        threads,
        fields=("tools", "models"),
        folder="30-tools-models",
        note_type="tool_model",
        report_path=report_path,
        report_contract=report_contract,
    )
    practice_notes = _term_notes(
        clean_week,
        threads,
        fields=("practices",),
        folder="40-practices",
        note_type="engineering_practice",
        report_path=report_path,
        report_contract=report_contract,
    )
    channel_notes = _channel_notes(
        clean_week,
        threads,
        report_path,
        report_contract=report_contract,
    )
    read_queue_notes = _read_queue_notes(
        clean_week,
        all_threads,
        report_path,
        read_atoms=projection.get("read_atoms") or [],
        report_contract=report_contract,
    )
    experiment_notes = _experiment_notes(
        clean_week,
        threads,
        report_path,
        experiment_actions=projection.get("experiment_actions") or [],
        project_watch=projection.get("project_watch") or [],
    )
    try_build_note = _try_build_note(
        clean_week,
        report_path,
        try_actions=projection.get("try_actions") or [],
        build_suggestions=projection.get("build_suggestions") or [],
        threads=all_threads,
    )
    project_watch_note = _project_watch_note(
        clean_week,
        report_path,
        project_watch=projection.get("project_watch") or [],
        threads=all_threads,
    )
    feedback_note = _feedback_summary_note(clean_week, report_path, feedback_summary)
    strategy_note = _strategy_review_note(clean_week, report_path, strategy_review)
    notes.extend(tool_model_notes)
    notes.extend(practice_notes)
    notes.extend(channel_notes)
    notes.extend(read_queue_notes)
    notes.extend(experiment_notes)
    notes.extend([try_build_note, project_watch_note, feedback_note, strategy_note])

    written: list[Path] = []
    for relative_path, content in notes:
        target = root / relative_path
        _write_generated_note(target, content)
        written.append(target)

    atoms = _all_atoms(all_threads)
    summary = ObsidianExportSummary(
        week_label=clean_week,
        vault_root=str(root),
        files_written=len(written),
        thread_count=len(threads),
        source_atom_count=len(atoms),
        term_note_count=len(tool_model_notes) + len(practice_notes),
        channel_note_count=len(channel_notes),
        read_queue_note_count=len(read_queue_notes),
        experiment_note_count=len(experiment_notes),
        try_build_note_count=1,
        project_watch_note_count=1,
        feedback_summary_note_count=1,
        strategy_review_note_count=1,
    )
    _manifest(root, clean_week, written, summary.__dict__)
    return summary
